{
  "bandit": {
    "repo": "https://github.com/PyCQA/bandit",
    "rev": "${rev}"
  },
  "ruff": {
    "repo": "https://github.com/astral-sh/ruff-pre-commit",
    "rev": "v${rev}"
  },
  "pip-audit": {
    "repo": "https://github.com/pypa/pip-audit",
    "rev": "v${rev}"
  },
  "pre-commit-hooks": {
    "repo": "https://github.com/pre-commit/pre-commit-hooks",
    "rev": "v${rev}"
  }
}
