name: PR Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/**'

env:
  POETRY_VERSION: 2.0.1

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.13.2-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: /.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Poetry packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: pip install poetry==${{ env.POETRY_VERSION }}

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      run: |
        eval $(poetry env activate)
        poetry run pytest --verbose --tb=short
